# version: "3.8"

x-dpdk_mojo_base: &dpdk_mojo_base
  working_dir: /home/mojo_user/dpdk_mojo
  logging:
    driver: json-file
    options:
      max-size: 50m
  stdin_open: true
  tty: true
  shm_size: 16000000000
  volumes:
    - .:/home/mojo_user/dpdk_mojo/
    - ~/.ssh:/home/mojo_user/.ssh:rw
    - dpdk_mojo_vscode_data_cache:/home/mojo_user/.vscode-server/data/User/globalStorage:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  environment:
    DISPLAY: host.docker.internal:0

volumes:
  dpdk_mojo_vscode_data_cache:
      external: false


services:
  dpdk_mojo_gpu_arm64: &dpdk_mojo_gpu_arm64
    <<: *dpdk_mojo_base
    restart: unless-stopped
    # NOTE: Reusing the c_binder_mojo image 
    image: josiahls/c_binder_mojo-arm64-gpu:${VERSION:-latest}
    profiles: ["gpu_arm64"]
    platform: linux/arm64
    # depends_on:
    #   - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  dpdk_mojo_cpu_arm64: &dpdk_mojo_cpu_arm64
    <<: *dpdk_mojo_base
    profiles: ["cpu_arm64"]
    restart: unless-stopped
    platform: linux/arm64
    # NOTE: Reusing the c_binder_mojo image 
    image: josiahls/c_binder_mojo-arm64-cpu:${VERSION:-latest}


  dpdk_mojo_gpu_x86_64: &dpdk_mojo_gpu_x86_64
    <<: *dpdk_mojo_base
    restart: unless-stopped
    # NOTE: Reusing the c_binder_mojo image 
    image: josiahls/c_binder_mojo-x86_64-gpu:${VERSION:-latest}
    profiles: ["gpu_x86_64"]
    platform: linux/amd64
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  dpdk_mojo_cpu_x86_64: &dpdk_mojo_cpu_x86_64
    <<: *dpdk_mojo_base
    profiles: ["cpu_x86_64"]
    restart: unless-stopped
    platform: linux/amd64
    # NOTE: Reusing the c_binder_mojo image 
    image: josiahls/c_binder_mojo-x86_64-cpu:${VERSION:-latest}
