 [project]
authors = ["josiahls <jklaivins@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "dpdk_mojo"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
mojo = ">=25.6.0.dev2025080116"
pre-commit = ">=4.2.0,<5"
pyelftools = ">=0.29"

[tasks]
######################### DPDK #######################################
clone_dpdk = { cmd = [
    "bash", "-c", 
    "if [ ! -d dpdk ]; then git clone https://github.com/DPDK/dpdk.git; else echo 'DPDK directory already exists.'; fi"
]}

init_build_dpdk = { cmd = [
    "cd", "dpdk", "&&",
    "meson", "-Dplatform=generic", "-Dmax_numa_nodes=1", "-Dexamples=all", "build"
], depends-on = [ 
    "clone_dpdk"
]}

build_dpdk = { cmd = [
    "cd", "dpdk", "&&",
    "ninja", "-C", "build"
], depends-on = [
    "init_build_dpdk"
], outputs = ["dpdk/build/lib/libdpdk.so"]}


######################### C Binder Mojo #######################################
clone_c_binder_mojo = { cmd = [
    "bash", "-c", 
    "if [ ! -d c_binder_mojo ]; then git clone https://github.com/josiahls/c_binder_mojo.git; else echo 'C Binder Mojo directory already exists.'; fi"
]}

try_symlink_c_binder_mojo = { cmd = [
    "./scripts/optional_symlinks.sh"
]}

checkout_c_binder_mojo = { cmd = [
    "cd", "c_binder_mojo", "&&",
    "git", "checkout", "feat/add-recursive-header-include"
], depends-on = [ "try_symlink_c_binder_mojo" ]}

######################### Core API ############################################
configure = { cmd = [
    "echo", "configuring"
], depends-on = [ "build_dpdk", "checkout_c_binder_mojo" ] }

generate_bindings = { cmd = [
    "./generate_bindings.sh"
], depends-on = [ "configure" ]}

format = { cmd = [
    "mojo", "format", "c_binder_mojo"
]}


######################### Tests ############################################

test_hello_world_c = { cmd = [
    "cd", "dpdk/build/examples", "&&",
    "./dpdk-helloworld", "--no-huge", "--file-prefix=test", "--proc-type=primary"
], depends-on = [ "build_dpdk" ]}

test_hello_world = { cmd = [
    "export", "LIBDPDK_LIB_PATH=$PIXI_PROJECT_ROOT/dpdk/build/lib/", "&&",
    "pixi", "run", "mojo", "run","-I",".", "-I", "c_binder_mojo", "tests/test_hello_world.mojo"
], depends-on = [ "init_dpdk_build", "generate_bindings" ]}

